### ISSUE TITLE
Object 'gene.pos' not found

### ISSUE THREAD

**Issue by rrlove** [ACAD-UofA/PolyLinkR#1]
Hello,

Attempting to run the example
```
output = polylinkr(obj.info = Anatolia_EF_CLR, 
set.info = PolyLinkR_SetInfo, set.obj = PolyLinkR_SetObj, 
n.cores = 8, emp.nruns = 10000, NN = 1000)
```
from the documentation, using R 3.3.1 or 3.6.0, errors out with 
```
Error in polylinkr(obj.info = Anatolia_EF_CLR, set.info = PolyLinkR_SetInfo,  : 
  object 'gene.pos' not found
```
Do I also need to load some other file or object?

This also happens when attempting to run the same code on gene scores and sets from my own data.  I did install PolyLinkR from a local directory, rather than using devtools, so that I could comment out lines 384-6, which were preventing successful installation. However, I think that's probably unrelated to this error.

**Comment by yassineS** [comment]
Hi rrlove,

The software is still in alpha version, and undergoing a major update that'll improve robustness. In the meantime we recommend using Josephine Daub's PolySel: https://github.com/CMPG/polysel or David Enard's method: https://github.com/DavidPierreEnard/Gene_Set_Enrichment_Pipeline to perform geneset enrichments while correcting for clustering and other confounding factors.

**Comment by rrlove** [comment]
Great, thank you for the alternative suggestions!
